runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: "/static"
  static_dir: static
  secure: optional
  expiration: 4d
  application_readable: true
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
  expiration: 4d
- url: .*
  script: fan.main.app

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
