api_version: 1
application: fan-ai
runtime: python27
threadsafe: yes
module: default

builtins:
- remote_api: on

handlers:
- url: "/static"
  static_dir: static
  secure: optional
  expiration: 4d
  application_readable: true
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
  expiration: 4d
- url: "/background/"
  script: fan._app.app
  secure: optional
  login: admin
- url: "/admin/"
  script: fan._app.app
  secure: optional
  login: admin
- url: .*
  script: fan._app.app
  secure: optional

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: ssl
  version: latest

skip_files:
- ^(.*/)?.*\.py[co]$
- node_modules/(.*)
- bower_components/(.*)
- config-def.yaml